### ISSUE TITLE
Suggestion: order barcodes by barcode fasta order

### ISSUE THREAD

**Issue by mp15** [PacificBiosciences/barcoding#1]
Currently in the reports barcodes are output in a lexicographical order which puts lbc5 in between lbc49 and lbc50. Might it be possible to output barcodes in the same order they are supplied in the barcode fasta?

**Comment by armintoepfer** [comment]
Which reports? The R plots?

**Comment by mp15** [comment]
Yes, I noticed the issue in the report_detail.R plots, where you have multiple plots on the same page.

**Comment by armintoepfer** [comment]
I'm happy to accept a patch.
