### ISSUE TITLE
What's the difference of the "Below min score lead" and "Below min score"?

### ISSUE THREAD

**Issue by WilsonCheng07** [PacificBiosciences/barcoding#2]
What are the difference of the "Below min score lead" and "Below min score"?
What are the filtering parameters for this two score?

**Comment by armintoepfer** [comment]
>Below min score
That's the mean barcode score. In SMRTlink, this is set to 26.

>Below min score lead
Score lead is the distance of the best combination of barcode to the next best combination. It gives you a feeling for, how reliable the candidate combination of barcodes is. Default is 10 and should not be changed for PacBio provided barcodes.

**Comment by WilsonCheng07** [comment]
Thank you for the detailed information!
Just want to confirm that I really understand the definition, if the number of "Below min score lead" is high, does it mean the reads are not easy to be separated by the given barcode or the quality of the reads is not really good? 
Thanks!

**Comment by armintoepfer** [comment]
It can be either or a combination! Have you tried to use generate the detail plots?
Are you using your own barcode sequences? If too many get removed by the score lead filter, it's an indication that barcodes can't be separated with sufficient reliability. Feel free to contact me at atoepfer ät pacb com
