### ISSUE TITLE
The recommended minimum barcode score in lima

### ISSUE THREAD

**Issue by alimayy** [PacificBiosciences/barcoding#4]
Hi, thanks for developing lima. I have a quick question: does the recommended minimum barcode score for lima correspond to that in earlier SMRT Link demultiplexing practices (e.g. 45)? Otherwise what is your recommendation? 

I've done some tests and realised that when I use 45 in lima, in one SMRT Cell 928 Mb of a 3,48 Gb total yield is not split into any of the demultiplexed samples. Just wondering if this score is too high.

**Comment by armintoepfer** [comment]
Can you please post the content of the `*.summary` file or contact me at atoepfer-ät-pacificbiosciences-com?
We tested extensively and SMRTlink 5.1 will use a score threshold of 26. But generally, lima removes the majority of unreliable calls even without a hard score cutoff using more sophisticated internal filters.

**Comment by alimayy** [comment]
Thanks for your reply. Sending the content to the specified address.

**Comment by armintoepfer** [comment]
Use 26 and you are safe. That's more than approximately the score of a random genomic DNA sequence against a barcode.

**Comment by alimayy** [comment]
Thanks a lot Armin, 26 works just fine for me.
