### ISSUE TITLE
Barcode names must contain either '3p' or '5p' suffix!

### ISSUE THREAD

**Issue by iwangtoknow** [PacificBiosciences/barcoding#7]
Hi Armin,
I met this error.
`lima p0.1.subreads.ccs.bam barcodes.fasta p0.1.subreads.demux.ccs.bam --isoseq --no-pbi`
```
root@4f7830d32f88:/data/F08_1_bam# cat barcodes.fasta 
>primer_5p
AAGCAGTGGTATCAACGCAGAGTAC
>primer_3p
GTACTCTGCGTTGATACCACTGCTT
```
I wonder what's my fault?
Thx.

**Comment by armintoepfer** [comment]
Do you have any weird line endings?
https://stackoverflow.com/questions/3569997/how-to-find-out-line-endings-in-a-text-file

**Comment by iwangtoknow** [comment]
Thanks Armin,
Sorry for replying so late, you are right, it's the problem with weird line endings.

**WANG**
